markdown: rdiscount
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]

name: Alex Solovey
url: http://veysby.github.io
twitter: veysby
gravatar_url: https://avatars3.githubusercontent.com/u/4071405
description: Coming soon...
